<div class="stream-container">
  <div class="content-header">
    <div class="header-inner">
      <h2>Tweets</h2>
    </div>
  </div>
  <div class="stream">
    <ol class="stream-items">
    <?php include 'tweet.inc'; ?>
    </ol>
  </div>
  <div class="twitter-footer">
    <div class="twitter-icon-inner">
        <img class="twitter-icon" src="assets/twitter.png" alt="image" >
    </div>
  </div>
</div>
